FROM node:24-alpine as frontend-build

WORKDIR /app

COPY frontend/package*.json .

RUN npm ci

COPY frontend/ .

RUN npm run build

FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY nginx/my_app.conf /etc/nginx/conf.d/default.conf

COPY --from=frontend-build /app/dist /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]