services:
  backend:
    build:
      context: ./backend
    container_name: cinebook_backend
    environment:
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - TZ=Africa/Tunis
      - MAIL=${MAIL}
      - API_KEY=${API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/cinebook_db
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
  db:
    image: postgres:17-alpine
    container_name: cinebook_db
    volumes:
      - ./backend/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_DB=cinebook_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cinebook_user -d cinebook_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:8.2-alpine
    container_name: cinebook_cache
    healthcheck:
      test: ["CMD","redis-cli","ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  nginx:
    build:
      context: . #Docker interdit de copier un fichier qui se trouve en dehors du build context.
      dockerfile: frontend/Dockerfile.prod
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend

